### ISSUE TITLE
Payment for access fee should be taken after a user has been inducted

### ISSUE THREAD

**Issue by harvy4002** [HACManchester/membership-system#134]
Talking to @conorriches it seems the payment of the access fee is taken when a user signs up for induction which leads to issues as the user sometimes doesn't even start the induction process. This money doesn't get refunded, as far as I can tell.
Coupled with the fact that anyone can add a name to the waiting list, means it can be open to abuse.
I proposed we change it so only when a member is inducted then money will be taken.

**Comment by rjackson** [comment]
Given how constrained we sometimes are with voluntary resource, there have been discussions that more equipment should charge access fees for _requesting_ inductions – to discourage members signing up and immediately requesting inductions on absolutely everything.

We could discuss this further, but I don't think we should worry too much about _when_ we charge somebody their access fee.

It's also worth bearing in mind it decrements a member's online balance, and that balance can go negative – so that cost isn't immediately incurred until the member tops up their balance.

As a side-note, we have a lot of members right now with negative balances in the system – perhaps not knowing that they have to top up to pay off their balance, but the numbers are so low at the minute it's been judged as not worth the effort trying to chase / recoup.

>Coupled with the fact that anyone can add a name to the waiting list, means it can be open to abuse.

The "Add a member" box on equipment pages is only accessible to trainers or admins, and does not charge training fees at all.

**Comment by harvy4002** [comment]
So to be clear if a member requests an indiction, it will clearly state they will be charged (whether they read it or not) and then they join the wait list.
If a trainer adds a member to the wait list then they won't be charged but still added to the list.

**Comment by rjackson** [comment]
Yep, both of those statements are correct!
