### ISSUE TITLE
Rebuild public/queryN.php scripts in Laravel

### ISSUE THREAD

**Issue by rjackson** [HACManchester/membership-system#74]
As identified in #67 and chatting to Connor, we have a bunch of scripts in our public directory that are used / referenced by other systems, such as how the space's door controller knows what access codes & key fobs to grant access.

```txt
public/query2-booking.php
public/query2.php
public/query2_bkup.php
public/query2b.php
public/query2v.php
public/query3.php
public/query7.php
public/text.php
```

We can't directly bring these files into the repository as they contain hardcoded credentials. Work would be required to load credentials through Laravel, at which point we might as well just rebuild the functionality directly in Laravel – or extend the (related?) `/acs` functionality?

With Laravel's routing, we can probably maintain the same URLs as the existing scripts – so no changes would be required for any external systems.

Rough task list:

- [x] Review access logs to identify which of these scripts are still actively used (usage counts within the last year?)
- [ ] Create new public methods on `AcsController` for any new endpoints
- [ ] Set up new routes for each endpoint (with clearer / more descriptive names)
- [ ] Set up a separate route on the old script names to maintain backwards compatibility for existing integrations

**Comment by conorriches** [comment]
Thanks for taking a look! 🛠️

You're right that `query2.php` is what's used for the entry system(s).

It's being polled by two different devices:
* The Raspberry Pi which operates the on-door rectangular fob reader. This Pi is mounted inside the big square push to exit button.
* The Raspberry Pi which operates the on-wall keypad. This is mounted in the enclosure on the wall with the LCD display. This will soon also operate a square on-wall fob reader under the keypad, so that we have an entirely parallel fob system.

These systems are separate and run in parallel as the fob system is old as dirt and is actually a Pi 1 and can't be upgraded easily due to hardware reasons. I don't want to go anywhere near this system and instead built something more modern alongside it 😅

They both in theory update every 5 minutes - they simply take the file and dump the contents into a file locally called `members.csv`. this way, if the internet goes down, the door will still work as no network requests are needed to be made when someone scans their fob.

It updates so frequently because people rightly expect to set up a fob then immediately test it on the door. 

In terms of pulling these scripts into Laravel - I'd strongly suggest we keep them separate, at least for now, so that if Laravel breaks, the door won't break. 

As this endpoint is the interface between the membership system and the physical door, we also do need to keep this operating. The software for the fob controller isn't easy to update as it's done with Ansible which only two members have permission to update.

The fob reader can be more easily updated and I've considered adding in extra columns in the `members.csv` file such as "remember to do the general induction" or "there is a message for you on the membership system" (such as reminders about confirming your email, adding a photo etc).

Installing the new fob reader is dependent on someone confident with the SDS drill installing it, which isn't me. So there's no rush for now. 

Sadly I think this is something that is just needed for historical reasons, until the door operates on the new Pi system

**Comment by rjackson** [comment]
>In terms of pulling these scripts into Laravel - I'd strongly suggest we keep them separate, at least for now, so that if Laravel breaks, the door won't break.

I understand the fear, but I believe the file sitting on the Raspberry Pis should serve as the backup scenario in that case? If Laravel ends up in a broken state when the Pi's check in, they shouldn't refresh their local file (we won't be responding with a `Content-Disposition` header)?

I've ended up looking at this as part of the redeployment work, as I couldn't make HACManchester/membership-deployment#4 work. It might be worth framing this task as a step toward the redeployment, the goal of which is to gain more control & confidence in our deployment of the system.

One of the benefits of the approach I want to put in place is that the server will have multiple versions of the code sitting, pre-built, ready to deploy on the server. If we ever have any issues with Laravel, we'll be able to instantly revert to the previous working versions.

Does that help alleviate any fears about bringing this back into Laravel?

A separate option I could explore is keeping the script separate, but extend it to extract the database credentials from our `.env` file? That will let us bring it into version control and allow me to progress with the redeployment work.

Without going through Laravel we wouldn't have the convenience of loading configuration via `phpdotenv`, but I'm sure I could make that work. We'd still be serving the file from the same webserver as the membership system, but it wouldn't depend on Laravel as a runtime at least.

**Comment by rjackson** [comment]
Yeah no worries :) I have half the code on another machine for that Laravel-driven endpoint. The actual looking up of data is easy, but I've yet to tackle API authentication yet.

To keep things moving, I'm wanting to bring `public/query2.php` into the repository but have it look up credentials from `.env`.
